name       : duktape
version    : 2.6.0
release    : 2
source     :
    - https://github.com/svaarala/duktape/releases/download/v2.6.0/duktape-2.6.0.tar.xz : 96f4a05a6c84590e53b18c59bb776aaba80a205afbbd92b82be609ba7fe75fa7
license    : MIT
component  : programming.library
homepage   : https://duktape.org
summary    : Embeddable JavaScript engine with a focus on portability and compact footprint
description: |
    Duktape is an embeddable JavaScript engine, with a focus on portability and compact footprint.
setup      : |
    sed -i 's|INSTALL_PREFIX = /usr/local|INSTALL_PREFIX = $(installdir)/usr|' Makefile.sharedlibrary
    sed -i 's|-Wall -Wextra -Os|$(CFLAGS) -DDUK_USE_FASTINT|' Makefile.sharedlibrary
build      : |
    %make -f Makefile.sharedlibrary
install    : |
    %make_install -f Makefile.sharedlibrary
    rm -v $installdir/usr/lib/libduktaped.*
