name       : duktape
version    : 2.7.0
release    : 4
source     :
    - https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz : 90f8d2fa8b5567c6899830ddef2c03f3c27960b11aca222fa17aa7ac613c2890
license    : MIT
component  : system.base
homepage   : https://duktape.org
summary    : Embeddable JavaScript engine with a focus on portability and compact footprint
description: |
    Duktape is an embeddable JavaScript engine, with a focus on portability and compact footprint.
environment: |
    export CFLAGS="$CFLAGS -DDUK_USE_FASTINT"
setup      : |
    %patch --strip=2 < $pkgfiles/force-libm.patch
build      : |
    %make -f Makefile.sharedlibrary
install    : |
    %make_install -f Makefile.sharedlibrary INSTALL_PREFIX=/usr/
    rm -v $installdir/usr/lib/libduktaped.*
